#!/usr/bin/env python3

from test_driver import TestDriver
from kim_test_utils.test_driver import query_crystal_genome_structures
from ast import literal_eval

model_name = input("Model name?\n")
print(model_name)
stoichiometric_species = literal_eval(input("Stoichiometric species?\n"))
print(stoichiometric_species)
prototype_label = input("Prototype label?\n")
print(prototype_label)
runtime_args = literal_eval(input("Runtime arguments (dictonary)?\n"))
print(runtime_args)
test = TestDriver(model_name)
# TODO: generalize this for finite temperature and pressure
cg_des_list = query_crystal_genome_structures(model_name,stoichiometric_species,prototype_label)
for cg_des in cg_des_list:    
    test(**cg_des,**runtime_args)
test.write_property_instances_to_file()